BookShoppingCartMvc/BookShoppingCartMvcUI/Controllers/BookServiceController.cs
using BookShoppingCartMvcUI.Data;
using BookShoppingCartMvcUI.Models;
using BookShoppingCartMvcUI.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShoppingCartMvcUI.Controllers
{
    public class BookServiceController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IBookRepository _bookRepo;
        private readonly ApplicationDbContext _db;

        public BookServiceController(IWebHostEnvironment webHostEnvironment, IBookRepository bookRepo, ApplicationDbContext db)
        {
            _webHostEnvironment = webHostEnvironment;
            _bookRepo = bookRepo;
            _db = db;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateBook(Book book, IFormFile? imageFile, string deleteImageFile)
        {
            if (!string.IsNullOrEmpty(deleteImageFile))
            {
                imageFile = null;
                book.Image = null;
            }

            book.Genre = _db.Genres.Find(book.GenreId);

            if (!(string.IsNullOrEmpty(book.BookName) || string.IsNullOrEmpty(book.AuthorName) || book.Price == 0 || book.GenreId == 0))
            {
                await _bookRepo.Create(book, imageFile, _webHostEnvironment);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditBook(Book bookModel, IFormFile? imageFile, string deleteImageFile)
        {
            var bookForEdit = _db.Books.Find(bookModel.Id);
            if (bookForEdit == null) throw new InvalidOperationException("Book not found.");

            if (!string.IsNullOrEmpty(deleteImageFile))
            {
                imageFile = null;
                if (!string.IsNullOrEmpty(bookForEdit.Image))
                {
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", bookForEdit.Image);

                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }
                bookForEdit.Image = null;
            }

            if (!(string.IsNullOrEmpty(bookModel.BookName) || string.IsNullOrEmpty(bookModel.AuthorName) || bookModel.Price == 0 || bookModel.GenreId == 0))
            {
                await _bookRepo.Edit(bookModel, bookForEdit, imageFile, _webHostEnvironment);

                return RedirectToAction("Index", "Home");
            }

            return View(bookForEdit);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteBook(Book bookModel)
        {
            var book = _db.Books.Find(bookModel.Id);
            if (book != null)
            {
                _bookRepo.Delete(book, _webHostEnvironment);
                return RedirectToAction("Index", "Home");
            }

            return NotFound();
        }
    }
}

BookShoppingCartMvc/BookShoppingCartMvcUI/Controllers/HomeController.cs
using BookShoppingCartMvcUI.Models;
using BookShoppingCartMvcUI.Models.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookShoppingCartMvcUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeRepository _homeRepository;

        public HomeController(ILogger<HomeController> logger, IHomeRepository homeRepository)
        {
            _homeRepository = homeRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string sterm = "", int genreId = 0)
        {
            IEnumerable<Book> books = await _homeRepository.GetBooks(sterm, genreId);
            IEnumerable<Genre> genres = await _homeRepository.Genres();
            BookDisplayModel bookModel = new BookDisplayModel
            {
                Books = books,
                Genres = genres,
                STerm = sterm,
                GenreId = genreId
            };

            return View(bookModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookShoppingCartMvc/BookShoppingCartMvcUI/Views/Home/Index.cshtml
@model BookShoppingCartMvcUI.Models.DTOs.BookDisplayModel
@{

}

<style>
    #search_block {
        margin-top: 20px;
        margin-bottom: 20px;
    }
    #card_body p{
        color: black;
    }
</style>

<div  class="d-flex justify-content-center">
    <div id="search_block">
        <form asp-action="Index" class="row row-cols-lg-auto g-3 align-items-center">
            <div class="col-12">
                <label class="visually-hidden" for="genreId">Genres</label>
                <select class="form-select" id="genreId" name="genreId">
                    <option selected>Choose...</option>
                    @foreach(var genre in Model.Genres)
                    {
                        <option selected="@(genre.Id == Model.GenreId)" value="@genre.Id">@genre.GenreName</option>
                    }
                </select>
            </div>

            <div class="col-12">
                <label class="visually-hidden" for="sterm">Search by title</label>
                <div class="input-group">
                    <div class="input-group-text"></div>
                    <input type="text" class="form-control" value="@Model.STerm" id="sterm" name="sterm" placeholder="Search by title">
                </div>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary">Search</button>
                <a href="/Home/Index" class="btn btn-dark">Reset</a>
                @if (User.IsInRole("Admin"))
                {
                    <a href="/BookService/CreateBook" class="btn btn-primary">Create New Book</a>
                }
            </div>
        </form>
    </div>
</div>

<div class="w-100 mt-4 d-flex justify-content-center flex-wrap">
    @foreach (var book in Model.Books)
    {
        <div class="card mx-3 mb-4" style="width: 11rem;">
            @if (string.IsNullOrEmpty(book.Image))
            {
                <img style="width:auto; height:250px" src="/images/noimage.jpg" class="card-img-top" alt="...">
            }
            else
            {
                <img style="width:auto; height:250px" src="/images/@book.Image" class="card-img-top" alt="...">
            }
            <div class="card-body" id="card_body">
                <h5 class="card-title"><b>@book.BookName</b></h5>
                <p class="card-text">
                    <b>Genre: </b>@book.GenreName <br/>
                    <b>Author: </b>@book.AuthorName <br/>
                    <b>Price: </b>@book.Price
                </p>
            </div>
            <div>
                @if (!User.IsInRole("Admin"))
                {
                    <button type="button" onclick="add(@book.Id)" class="btn btn-primary" style="margin-left: 35px; margin-bottom: 10px">Add to cart</button>
                }
                else
                {
                    <a asp-controller="BookService" asp-action="EditBook" asp-route-id="@book.Id" class="btn btn-primary" style="margin-left: 23px; margin-bottom: 10px">Edit</a>
                    <button type="button" class="btn btn-danger" style="margin-bottom: 10px" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal-@book.Id">Delete</button>
            
                    <div class="modal fade" id="deleteConfirmationModal-@book.Id" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Deletion</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete the book "@book.BookName"?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                    <a asp-controller="BookService" asp-action="DeleteBook" asp-route-id="@book.Id" class="btn btn-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
</div>

@section Scripts{
    <script>
        async function add(bookId)
        {
            var usernameEl = document.getElementById("username");
            if(usernameEl == null)
            {
                window.location.href="/Identity/Account/Login";
            }
            try
            {
                var response = await fetch(`/Cart/AddItem?bookId=${bookId}`);
                if(response.status == 200)
                {
                    var result = await response.json();
                    var cartCountEl = document.getElementById("cartCount");
                    cartCountEl.innerHTML = result;
                    window.location.href = "#cartCount";
                }
            }
            catch(err)
            {
                console.log(err);
            }
        }
    </script>
}